export const speciesImages: Record<string, string[]> = {
  "Chilodonella uncinata": [
    "/Visualisations/c_bp/1_c_bp.jpg",
    "/Visualisations/c_pe/1_c_pe.jpg",
    "/Visualisations/mfe_bp/1_mfe_bp.jpg",
    "/Visualisations/mfe_pe/1_mfe_pe.jpg",
    "/Visualisations/mountain_plot/1_plot.png",
  ],
  "Parvochelus russus": [
    "/Visualisations/c_bp/2_c_bp.jpg",
    "/Visualisations/c_pe/2_c_pe.jpg",
    "/Visualisations/mfe_bp/2_mfe_bp.jpg",
    "/Visualisations/mfe_pe/2_mfe_pe.jpg",
    "/Visualisations/mountain_plot/2_plot.png",
  ],
  "Encephalitozoon intestinalis": [
    "/Visualisations/c_bp/3_c_bp.jpg",
    "/Visualisations/c_pe/3_c_pe.jpg",
    "/Visualisations/mfe_bp/3_mfe_bp.jpg",
    "/Visualisations/mfe_pe/3_mfe_pe.jpg",
    "/Visualisations/mountain_plot/3_plot.png",
  ],
  "Caecitellus parvulus": [
    "/Visualisations/c_bp/4_c_bp.jpg",
    "/Visualisations/c_pe/4_c_pe.jpg",
    "/Visualisations/mfe_bp/4_mfe_bp.jpg",
    "/Visualisations/mfe_pe/4_mfe_pe.jpg",
    "/Visualisations/mountain_plot/4_plot.png",
  ],
  "Dasytricha ruminantium": [
    "/Visualisations/c_bp/5_c_bp.jpg",
    "/Visualisations/c_pe/5_c_pe.jpg",
    "/Visualisations/mfe_bp/5_mfe_bp.jpg",
    "/Visualisations/mfe_pe/5_mfe_pe.jpg",
    "/Visualisations/mountain_plot/5_plot.png",
  ],
  "Diutina catenulata": [
    "/Visualisations/c_bp/8_c_bp.jpg",
    "/Visualisations/c_pe/8_c_pe.jpg",
    "/Visualisations/mfe_bp/8_mfe_bp.jpg",
    "/Visualisations/mfe_pe/8_mfe_pe.jpg",
    "/Visualisations/mountain_plot/8_plot.png",
  ],
  "Unknown": [
    "/Visualisations/c_bp/9_c_bp.jpg",
    "/Visualisations/c_pe/9_c_pe.jpg",
    "/Visualisations/mfe_bp/9_mfe_bp.jpg",
    "/Visualisations/mfe_pe/9_mfe_pe.jpg",
    "/Visualisations/mountain_plot/9_plot.png",
  ],
  "Strigamia maritima": [
    "/Visualisations/c_bp/10_c_bp.jpg",
    "/Visualisations/c_pe/10_c_pe.jpg",
    "/Visualisations/mfe_bp/10_mfe_bp.jpg",
    "/Visualisations/mfe_pe/10_mfe_pe.jpg",
    "/Visualisations/mountain_plot/10_plot.png",
  ],
};